### ISSUE TITLE
lint: Add Export documentation rules

### ISSUE THREAD

**Issue by MSevey** [celestiaorg/celestia-node#1327]
With the `revive` linter replacing `golint` within `golangci-lint`, the check for exports having documentation has been disabled by default. 

This should be re-enabled as all exports should have documentation and reviews are having to check for this unnecessarily. 

```yml
linters:
  enable:
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments
```

See https://www.pixelstech.net/article/1650069870-golangci-lint-to-enable-comment-check-for-exported-functions
