### ISSUE TITLE
ci: create jobs for different configurations

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#1584]
We have faced issues when tests pass on Linux and fail on MacOs(and vice versa). I think we should create jobs and run tests on both platforms. Not sure, that we have to run them on each push, but we should definitely do this before our changes will be merged in the main branch.

**Comment by MSevey** [comment]
you can add macos as a os type in the github actions
```
jobs:
  build:
    runs-on: macos-latest
```
then we can run the CI on both like so

```
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
```
