### ISSUE TITLE
Attempt to spin up a DA light client node fails when bind-mounting the celestia block dir from docker compose

### ISSUE THREAD

**Issue by appetrosyan** [celestiaorg/celestia-node#2799]
### Celestia Node version

ghcr.io/celestiaorg/celestia-app:v1.0.0-rc14

### OS

Alpine linux

### Install tools

Docker, with docker compose

### Steps to reproduce it

1. Create `docker-compose.yml` with the following contents
```yaml
version: '3'
services:
  celestia:
    build: ./celestia
    volumes:
     - ./.local_data/celestia:/home/celestia
    ports:
      - "26657:26657"
      - "26658:26658"
      - "26659:26659"
      - "9090:9090"

  #use ganache for now
  eth:
    # image: trufflesuite/ganache-cli:latest
    build: ./eth
    ports:
      - "8545:8545"
    volumes:
      - ./.local_data/ganache_data:/ganache_data
    entrypoint:
      - ganache
      - --database.dbPath=/ganache_data
      - -m
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - -h
      - '0.0.0.0'

  # build is extremely slow inside docker on m1 mac, might still want to run this externally or just connect to our own devnet
  # solana:
  #   build: ./solana
  #   ports:
  #     - "8899:8899"
  #     - "8900:8900"
  #     - "8001:8001"
  #   mem_limit: 8G

```

2. Create a ganache network via :

```dockerfile
FROM node:18-bullseye-slim as base

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        build-essential \
        python3 && \
    rm -fr /var/lib/apt/lists/* && \
    rm -rf /etc/apt/sources.list.d/*

RUN npm install --global --quiet npm truffle ganache

FROM base as truffle

RUN mkdir -p /home/app
WORKDIR /home/app

COPY package.json /home/app
COPY package-lock.json /home/app

RUN npm install --quiet

COPY truffle-config.js /home/app
COPY contracts /home/app/contracts
COPY migrations /home/app/migrations/
COPY test /home/app/test/

CMD ["truffle", "version"]

FROM base as ganache

RUN mkdir -p /home
WORKDIR /home
EXPOSE 8545

# ENTRYPOINT ["ganache", "--hostname 0.0.0.0"]
```

3. Docker file for `celestia`

```dockerfile
# from https://github.com/rollkit/local-celestia-devnet
FROM ghcr.io/celestiaorg/celestia-app:v1.0.0-rc14 AS celestia-app

FROM ghcr.io/celestiaorg/celestia-node:v0.11.0-rc12

USER root

# hadolint ignore=DL3018
RUN apk --no-cache add \
        curl \
        jq \
    && mkdir /bridge \
    && chown celestia:celestia /bridge

USER celestia

COPY --from=celestia-app /bin/celestia-appd /bin/

COPY entrypoint.sh /opt/entrypoint.sh

EXPOSE 26657 26658 26659 9090

ENTRYPOINT [ "/bin/bash", "/opt/entrypoint.sh" ]
```
4. Finally add `entrypoint.sh` with the following contents

```bash
#!/usr/bin/env bash

CHAINID="test"

# App & node has a celestia user with home dir /home/celestia
APP_PATH="/home/celestia/.celestia-app"
NODE_PATH="/home/celestia/bridge/"

#Check if the folder exists
if [ -d "$APP_PATH" ]; then
  # If it exists, do nothing
  echo "Folder exists, using existing config"
else
  # If it doesn't exist, print a message
  echo "The folder $APP_PATH does not exist."
  # Build genesis file incl account for passed address
  coins="1000000000000000utia"
  celestia-appd init $CHAINID --chain-id $CHAINID
  celestia-appd keys add validator --keyring-backend="test"
  # this won't work because some proto types are declared twice and the logs output to stdout (dependency hell involving iavl)
  celestia-appd add-genesis-account $(celestia-appd keys show validator -a --keyring-backend="test") $coins
  celestia-appd gentx validator 5000000000utia \
    --keyring-backend="test" \
    --chain-id $CHAINID

  celestia-appd collect-gentxs

  # Set proper defaults and change ports
  # If you encounter: `sed: -I or -i may not be used with stdin` on MacOS you can mitigate by installing gnu-sed
  # https://gist.github.com/andre3k1/e3a1a7133fded5de5a9ee99c87c6fa0d?permalink_comment_id=3082272#gistcomment-3082272
  sed -i'.bak' 's#"tcp://127.0.0.1:26657"#"tcp://0.0.0.0:26657"#g' ~/.celestia-app/config/config.toml
  sed -i'.bak' 's/timeout_commit = "25s"/timeout_commit = "1s"/g' ~/.celestia-app/config/config.toml
  sed -i'.bak' 's/timeout_propose = "3s"/timeout_propose = "1s"/g' ~/.celestia-app/config/config.toml
  sed -i'.bak' 's/index_all_keys = false/index_all_keys = true/g' ~/.celestia-app/config/config.toml
  sed -i'.bak' 's/mode = "full"/mode = "validator"/g' ~/.celestia-app/config/config.toml

  # Register the validator EVM address
  {
    # wait for block 1
    sleep 20

    # private key: da6ed55cb2894ac2c9c10209c09de8e8b9d109b910338d5bf3d747a7e1fc9eb9
    celestia-appd tx qgb register \
      "$(celestia-appd keys show validator --home "${APP_PATH}" --bech val -a)" \
      0x966e6f22781EF6a6A82BBB4DB3df8E225DfD9488 \
      --from validator \
      --home "${APP_PATH}" \
      --fees 30000utia -b block \
      -y
  } &

  mkdir -p $NODE_PATH/keys
  cp -r $APP_PATH/keyring-test/ $NODE_PATH/keys/keyring-test/

fi

# Start the celestia-app
celestia-appd start &

# Try to get the genesis hash. Usually first request returns an empty string (port is not open, curl fails), later attempts
# returns "null" if block was not yet produced.
GENESIS=
CNT=0
MAX=30
while [ "${#GENESIS}" -le 4 -a $CNT -ne $MAX ]; do
	GENESIS=$(curl -s http://127.0.0.1:26657/block?height=1 | jq '.result.block_id.hash' | tr -d '"')
	((CNT++))
	sleep 1
done

export CELESTIA_CUSTOM=test:$GENESIS
echo $CELESTIA_CUSTOM

celestia bridge init --node.store /home/celestia/bridge
export CELESTIA_NODE_AUTH_TOKEN=$(celestia bridge auth admin --node.store ${NODE_PATH})
echo "WARNING: Keep this auth token secret **DO NOT** log this auth token outside of development. CELESTIA_NODE_AUTH_TOKEN=$CELESTIA_NODE_AUTH_TOKEN"
celestia bridge start \
  --node.store $NODE_PATH --gateway \
  --core.ip 127.0.0.1 \
  --keyring.accname validator \
  --gateway.deprecated-endpoints
```

### Expected result

Network starts as expected; specifically:
```
docker-celestia-1  | Folder exists, using existing config
docker-celestia-1  | 2:33PM INF starting node with ABCI Tendermint in-process
docker-celestia-1  | 2:33PM INF service start impl=multiAppConn module=proxy msg={}
docker-celestia-1  | 2:33PM INF service start connection=query impl=localClient module=abci-client msg={}
docker-celestia-1  | 2:33PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
docker-celestia-1  | 2:33PM INF service start connection=mempool impl=localClient module=abci-client msg={}
docker-celestia-1  | 2:33PM INF service start connection=consensus impl=localClient module=abci-client msg={}
docker-celestia-1  | 2:33PM INF service start impl=EventBus module=events msg={}
docker-celestia-1  | 2:33PM INF service start impl=PubSub module=pubsub msg={}
docker-celestia-1  | 2:33PM INF service start impl=IndexerService module=txindex msg={}
docker-celestia-1  | 2:33PM INF ABCI Handshake App Info hash=":����\r�\x05�p#ze2�z%K\x02}v��GF\x0e\x1doe�\x7f�" height=109 module=consensus protocol-version=1 software-version=1.0.0-rc14
docker-celestia-1  | 2:33PM INF ABCI Replay Blocks appHeight=109 module=consensus stateHeight=109 storeHeight=109
docker-celestia-1  | 2:33PM INF Completed ABCI Handshake - CometBFT and App are synced appHash=":����\r�\x05�p#ze2�z%K\x02}v��GF\x0e\x1doe�\x7f�" appHeight=109 module=consensus
docker-celestia-1  | 2:33PM INF Version info abci=0.17.0 block=11 cmtbft_version=0.34.28 commit_hash= p2p=8
docker-celestia-1  | 2:33PM INF This node is a validator addr=BA4385AC51DED3ADB51083D87D0709943AF6391E module=consensus pubKey=bPGawdqQkBd1v+fC8tAAEPo5Mmla+mYkTmUHgEUAhvg=
docker-celestia-1  | 2:33PM INF P2P Node ID ID=a5c248134a7b2552e49326e0da714d88322a3339 file=/home/celestia/.celestia-app/config/node_key.json module=p2p
docker-celestia-1  | 2:33PM INF Adding persistent peers addrs=[] module=p2p
docker-celestia-1  | 2:33PM INF Adding unconditional peer ids ids=[] module=p2p
docker-celestia-1  | 2:33PM INF Add our address to book addr={"id":"a5c248134a7b2552e49326e0da714d88322a3339","ip":"0.0.0.0","port":26656} book=/home/celestia/.celestia-app/config/addrbook.json module=p2p
docker-celestia-1  | 2:33PM INF service start impl=Node msg={}
docker-celestia-1  | 2:33PM INF Starting pprof server laddr=localhost:6060
docker-celestia-1  | 2:33PM INF service start impl="P2P Switch" module=p2p msg={}
docker-celestia-1  | 2:33PM INF service start impl=Mempool msg={}
docker-celestia-1  | 2:33PM INF serve module=rpc-server msg={}
docker-celestia-1  | 2:33PM INF service start impl=BlockchainReactor module=blockchain msg={}
docker-celestia-1  | 2:33PM INF service start impl=ConsensusReactor module=consensus msg={}
docker-celestia-1  | 2:33PM INF Reactor  module=consensus waitSync=false
docker-celestia-1  | 2:33PM INF service start impl=ConsensusState module=consensus msg={}
docker-celestia-1  | 2:33PM INF service start impl=baseWAL module=consensus msg={} wal=/home/celestia/.celestia-app/data/cs.wal/wal
docker-celestia-1  | 2:33PM INF service start impl=Group module=consensus msg={} wal=/home/celestia/.celestia-app/data/cs.wal/wal
docker-celestia-1  | 2:33PM INF service start impl=TimeoutTicker module=consensus msg={}
docker-celestia-1  | 2:33PM INF Searching for height height=110 max=0 min=0 module=consensus wal=/home/celestia/.celestia-app/data/cs.wal/wal
docker-celestia-1  | 2:33PM INF Searching for height height=109 max=0 min=0 module=consensus wal=/home/celestia/.celestia-app/data/cs.wal/wal
docker-celestia-1  | 2:33PM INF Found height=109 index=0 module=consensus wal=/home/celestia/.celestia-app/data/cs.wal/wal
docker-celestia-1  | 2:33PM INF Catchup by replaying consensus messages height=110 module=consensus
docker-celestia-1  | 2:33PM INF Replay: Done module=consensus
docker-celestia-1  | 2:33PM INF service start impl=Evidence module=evidence msg={}
docker-celestia-1  | 2:33PM INF service start impl=StateSync module=statesync msg={}
docker-celestia-1  | 2:33PM INF service start impl=PEX module=pex msg={}
docker-celestia-1  | 2:33PM INF service start book=/home/celestia/.celestia-app/config/addrbook.json impl=AddrBook module=p2p msg={}
docker-celestia-1  | 2:33PM INF Saving AddrBook to file book=/home/celestia/.celestia-app/config/addrbook.json module=p2p size=0
docker-celestia-1  | 2:33PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
docker-celestia-1  | 2:33PM INF No addresses to dial. Falling back to seeds module=pex
docker-celestia-1  | 2:33PM INF starting API server... module=api-server
docker-celestia-1  | 2:33PM INF serve module=api-server msg={}
```

### Actual result

Celestia light client fails to start meaning that the following output is produced instead of the expected. 

### Relevant log output

```Shell
Attaching to docker-celestia-1, docker-eth-1
docker-celestia-1  | The folder /home/celestia/.celestia-app does not exist.
docker-celestia-1  | Error: couldn't make client config: mkdir /home/celestia/.celestia-app: permission denied
docker-celestia-1  | Error: couldn't make client config: mkdir /home/celestia/.celestia-app: permission denied
docker-celestia-1  | Error: couldn't make client config: mkdir /home/celestia/.celestia-app: permission denied
docker-celestia-1  | Error: accepts 2 arg(s), received 1
docker-celestia-1  | Error: couldn't make client config: mkdir /home/celestia/.celestia-app: permission denied
docker-celestia-1  | Error: couldn't make client config: mkdir /home/celestia/.celestia-app: permission denied
docker-celestia-1  | sed: /home/celestia/.celestia-app/config/config.toml: No such file or directory
docker-celestia-1  | sed: /home/celestia/.celestia-app/config/config.toml: No such file or directory
docker-celestia-1  | sed: /home/celestia/.celestia-app/config/config.toml: No such file or directory
docker-celestia-1  | sed: /home/celestia/.celestia-app/config/config.toml: No such file or directory
docker-celestia-1  | sed: /home/celestia/.celestia-app/config/config.toml: No such file or directory
docker-celestia-1  | mkdir: can't create directory '/home/celestia/bridge//': Permission denied
docker-celestia-1  | cp: can't stat '/home/celestia/.celestia-app/keyring-test/': No such file or directory
docker-celestia-1  | Error: couldn't make client config: mkdir /home/celestia/.celestia-app: permission denied
```

### Notes

Permissions for the actual location have been checked with `chmod 777` to ensure that the permissions were actually set right. It's possible that the location isn't exactly what we expect and the mistake is in the `docker-compose.yml`. 

This problem can be worked around if in the docker compose file the bind mount is disabled: 

```yaml
# volumes:
    # - ./.local_data/celestia:/home/celestia
```

**Comment by Bidon15** [comment]
Dear @appetrosyan, 

Thank you so much for opening this bug. After some debugging, I've found some nits that needs to be adapted in order to make the `compose.yaml` run as expected. Please take a look at this yaml snippet: 
```yaml
version: '3'
services:
  celestia:
    user: 10001:10001
    image: ghcr.io/rollkit/local-celestia-devnet:v0.11.0-rc12
    volumes:
      - ./.local_data/celestia:/home/celestia
    ports:
      - "26657:26657"
      - "26658:26658"
      - "26659:26659"
      - "9090:9090"

  #use ganache for now
  eth:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    volumes:
      - ./.local_data/ganache_data:/ganache_data
    command:
      - --database.dbPath=/ganache_data
      - -m
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - -h
      - '0.0.0.0'
```

As you can see, we have missed the user group assignment in docker-compose. After we've provided the `user:  10001:10001`(which is equal to `user: celestia:celestia`), the celestia app/node part is going to be started as expected.

I hope you are fine that ganache part has been redacted to make sure you can have expected behaviour of eth local blockchain. ganache-cli has been ditched in favour of ganache image. In addition, the image is using commands as args flags etc, so we have command instead of entrypoint. 

Let me know if it looks fine for you. 

Here is proof that this solution works in my mac: 
https://app.warp.dev/block/pLcBHNpAOdPlEA34iRlWkv

Cheers
