### ISSUE TITLE
celestia node grabbing excessive RAM

### ISSUE THREAD

**Issue by joroshiba** [celestiaorg/celestia-node#3129]
### Celestia Node version

0.12.3

### OS

Alpine 3.18.4

### Install tools

Using the ghcr docker container in k8s.  This is deployed with our helm chart: https://github.com/astriaorg/dev-cluster/tree/main/charts/celestia-node, utilizing an override which provides a PVC for storage.

k8s statefulset file:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: astria-celestia-node-light-mocha-4
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: astria-celestia-node-light-mocha-4
  serviceName: ''
  template:
    metadata:
      labels:
        app: astria-celestia-node-light-mocha-4
      name: astria-celestia-node-light-mocha-4
    spec:
      containers:
        - command:
            - ./celestia/scripts/start-node.sh
          image: 'ghcr.io/celestiaorg/celestia-node:v0.12.3'
          imagePullPolicy: IfNotPresent
          name: astria-celestia-node-light-mocha-4
          ports:
            - containerPort: 26658
              name: rpc
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 25Gi
            requests:
              cpu: '1'
              memory: 8Gi
          securityContext:
            runAsGroup: 10001
            runAsUser: 10001
          volumeMounts:
            - mountPath: /celestia/scripts
              name: astria-celestia-node-light-mocha-4-scripts-vol
            - mountPath: /celestia
              name: astria-celestia-node-light-mocha-4-vol
            - mountPath: /celestia/config.toml
              name: astria-celestia-node-light-mocha-4-files-volume
              subPath: config.toml
        - command:
            - /bin/httpd
            - '-v'
            - '-f'
            - '-p'
            - '5353'
            - '-h'
            - /celestia/token-server/
          image: 'busybox:1.35.0-musl'
          imagePullPolicy: IfNotPresent
          name: token-server
          ports:
            - containerPort: 5353
              name: token-svc
              protocol: TCP
          resources: {}
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /
              port: token-svc
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /celestia
              name: astria-celestia-node-light-mocha-4-vol
              readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
        - args:
            - '--node.store'
            - /celestia
          command:
            - /bin/celestia
            - light
            - init
          image: 'ghcr.io/celestiaorg/celestia-node:v0.12.3'
          imagePullPolicy: IfNotPresent
          name: init-astria-celestia-node-light-mocha-4
          volumeMounts:
            - mountPath: /celestia
              name: astria-celestia-node-light-mocha-4-vol
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
        runAsUser: 10001
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 484
            name: astria-celestia-node-light-mocha-4-scripts-env
          name: astria-celestia-node-light-mocha-4-scripts-vol
        - configMap:
            defaultMode: 420
            name: astria-celestia-node-light-mocha-4-files-env
          name: astria-celestia-node-light-mocha-4-files-volume
        - name: astria-celestia-node-light-mocha-4-vol
          persistentVolumeClaim:
            claimName: astria-celestia-node-light-mocha-4-storage-pvc
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
```

### Others

We have played around with the resources allocated to the light node, recently raising to 25GB of ram available, it consumes all available resources and then is killed to maintain safety. Can see init and commands in the above k8s stateful set.

### Steps to reproduce it

Deploy using helm chart w/ pvc configured. Very consistenly overconsimes

### Expected result

The node to not consume 25GB of ram and ideally be functional on stated minimum system requirements (500 MB?)

### Actual result

Can see graph of memory usage in GB of the node with each restart noted with different colors below
![image](https://github.com/celestiaorg/celestia-node/assets/459938/8fb740da-911a-4104-9f34-cc1cf326d443)
