### ISSUE TITLE
[Feature Request]: Allow using environment variables in addition to CLI arguments

### ISSUE THREAD

**Issue by kien-rise** [celestiaorg/celestia-node#4257]
### Implementation ideas

It would be great if Celestia could support environment variables in addition to CLI arguments.

What I meant is that the following two commands should be equivalent:

```sh
celestia light start --p2p.network mammoth --core.ip global.grpc.mamochain.com --core.port 9090 --rpc.skip-auth --node.store /home/celestia/store

CELESTIA_P2P_NETWORK=mammoth CELESTIA_CORE_IP=global.grpc.mamochain.com CELESTIA_CORE_PORT=9090 CELESTIA_RPC_SKIP_AUTH=true CELESTIA_NODE_STORE=/home/celestia/store celestia light start
```

**Motivation**
- Some global configs are used among different commands, e.g. `--p2p.network mammoth`, `--node.store /home/celestia/store`
- Using env vars has been a widely accepted technique. For example, Foundry's `cast` allow `ETH_RPC_URL='https://some-rpc-url.xyz' cast bn` in addition to `cast bn --rpc-url https://some-rpc-url.xyz`. Optimism's `op-batcher` allow `OP_BATCHER_THROTTLE_TX_SIZE`  in addition to `--throttle-tx-size`.

**Comment by walldiss** [comment]
Do you mind to add some details on what would be the benefit of using env vars instead of flags? Any specific usecase or setup that would benefit from it?

**Comment by kien-rise** [comment]
## Use case 1

From [Mammoth testnet docs](https://docs.celestia.org/how-to-guides/mammoth), if I want to use a customize the store dir, the process is:

```
celestia light init --p2p.network mammoth --node.store /path/to/store
celestia light start --p2p.network mammoth --node.store /path/to/store --core.ip global.grpc.mamochain.com --core.port 9090 --rpc.skip-auth
```

If env is allowed, the commands can be shortened to:

```
export CELESTIA_P2P_NETWORK=mammoth
export CELESTIA_NODE_STORE=/path/to/store
celestia light init
celestia light start --core.ip global.grpc.mamochain.com --core.port 9090 --rpc.skip-auth
```

## Use case 2

Another use case is when I add Celestia as a service to `docker-compose.yml`:

```yml
  celestia-da:
    image: ghcr.io/celestiaorg/celestia-node:v0.21.9-mammoth-v0.0.16
    ports:
      - "26658:26658"
    environment:
      NODE_TYPE: light
      NODE_STORE: /home/celestia/store
      P2P_NETWORK: mammoth
    command: "celestia light start --p2p.network mammoth --core.ip global.grpc.mamochain.com --core.port 9090 --rpc.skip-auth --node.store /home/celestia/store"
```

Notice that I have to specify `--p2p.network mammoth` and `--node.store /home/celestia/store` although `NODE_STORE` and `P2P_NETWORK` has been specified.

By supporting env vars, I expect something like:

```yml
  celestia-da:
    image: ghcr.io/celestiaorg/celestia-node:v0.21.9-mammoth-v0.0.16
    ports:
      - "26658:26658"
    environment:
      NODE_TYPE: light
      CELESTIA_NODE_STORE: /home/celestia/store
      CELESTIA_P2P_NETWORK: mammoth
    command: "celestia light start --core.ip global.grpc.mamochain.com --core.port 9090 --rpc.skip-auth"
```

Also, supporting env var will allow to customize the call to `celestia "${NODE_TYPE}" init`at https://github.com/celestiaorg/celestia-node/blob/main/docker/entrypoint.sh#L7. For example, I want to customize the `--rpc.addr="0.0.0.0"` argument.
