### ISSUE TITLE
Create Docker Image(s) for all commits

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/celestia-node#525]
Similar to https://github.com/celestiaorg/ethermint/blob/main/.github/workflows/build-evmos.yml we should build a celestia-node image in a Github action on every push.

The images can be tagged with the docker metadata action as below using the commit sha
```
uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
```
This will allow us to more easily run integration tests using the ephemeral cluster for specific changes. 

Things to keep in mind:
- Pushes to GHCR won't work from Pull Requests coming from forks
- We have unlimited free compute, storage, and bandwidth for Github actions and docker package storage as we're all OSS
